### ISSUE TITLE
how do i create dump file of my all migration?

### ISSUE THREAD

**Issue by Prajapatisantu** [narayandreamer/mysql2pgsql-docker#2]
my situation is :
 i have mysql database name youspin_development with all migration file and data available in database and now I want to change MySQL to PostgreSQL and I need to transfer MySQL data into PostgreSQL database so how can I do ?
if you have ans give me fast stepwise
 currently using:
docker
mysql

**Comment by narayanpromax** [comment]
Dump of MySQL is a pre-requisite for this tutorial to work. You can login to mysql shell and take a dump and use that or else install a tool like adminer of phpmyadmin and connect that to mysql to take the dump
